import time
import random
print("'Hey Kids! Today we'll be learning about why gambling is bad.'")
time.sleep(1.25)
answer = input("Are you ready? [Yes or No] ")
if answer == "Yes": print("'Good. Let us begin.'")
if answer == "No": print("'Too bad! We're starting.'")
time.sleep(1.25)
print("*you walk towards a slot machine*")
time.sleep(1.25)
print("'Alright, now spin the machine.'")
time.sleep(1.25)
choice1 = input("Do you spin the machine? [Yes or No] ")
if choice1 == "Yes": print('*The machine rumbles and spins*')
else: print('*The instructor pulls the lever for you*')
SlotValue = ("Cherry","7","King","Queen","Diamond")
Slot1 = random.choice(SlotValue)
Slot2 = random.choice(SlotValue)
Slot3 = random.choice(SlotValue)
time.sleep(2)
print("You got", Slot1, Slot2, "and", Slot3)